default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Android internal track"
  lane :beta do
    gradle(
    task: "assembleRelease"
    )
    #/Users/shashankgupta/research_work/reduxthunkdemonew/reduxdemo/android/app/gradle.properties
    git_commit(path: "/Users/vagrant/git/android/app/gradle.properties", message: "Version Bump Android [skip ci]")
    #push_to_git_remote(
    #  remote: "origin",        
     # remote_branch: "dev",
    #)
    #supply(
     #track: "internal",
     #apk: "/Users/vagrant/git/android/app/build/outputs/apk/release/app-release.apk"
    #)
  end
end
